# 协作举升任务地图配置
# 模拟 Human-Robot Gym 中的协作举升环境
# 基于 Human-Robot Gym 的配置：
# - table_full_size: [0.4, 1.5, 0.05]
# - table_offset: [1.0, 0.0, 0.8]
# - board_full_size: [1.0, 0.4, 0.03]

# 桌面配置 - 对应 Human-Robot Gym 的桌面
# 桌面位置：x=1.0, y=0.0, z=0.8 (对应 table_offset)
# 桌面尺寸：0.4×1.5×0.05 (对应 table_full_size)
# 格式：[x/WINDOW_W, y/WINDOW_H, angle] - 需要归一化到窗口尺寸
TABLE: [[0.5, 0.5, 0.0]]  # 桌面中心位置，无旋转

# 木板起始位置 - 对应 Human-Robot Gym 的木板
# 木板尺寸：1.0×0.4×0.03 (对应 board_full_size)
# 木板初始位置在桌面中央
BOARD_START: [1.0, 0.0, 0.85]

# 机器人起始位置 - 对应 Human-Robot Gym 的机器人位置
# 机器人站在桌面一侧，准备协作举升
ROBOT_START: [0.5, 0.0, 0.8]

# 人类起始位置 - 对应 Human-Robot Gym 的人类位置
# 人类站在桌面的另一侧，与机器人协作
HUMAN_START: [1.5, 0.0, 0.8]

# 协作区域 - 定义机器人和人类可以协作的空间
COLLABORATION_ZONE:
  CENTER: [1.0, 0.0, 0.8]
  RADIUS: 0.8  # 协作半径

# 木板举升目标位置 - 定义木板可以被举升到的位置
LIFT_TARGETS:
  - [1.0, 0.0, 1.2]  # 低举升位置
  - [1.0, 0.0, 1.5]  # 中举升位置  
  - [1.0, 0.0, 1.8]  # 高举升位置

# 安全区域 - 定义机器人和人类的安全工作空间
SAFETY_ZONES:
  ROBOT: [0.3, 0.7, 0.8]  # 机器人安全区域中心
  HUMAN: [1.3, 1.7, 0.8]  # 人类安全区域中心

# 障碍物配置 - 协作举升任务中通常没有障碍物
# 设置三个远离工作区域的障碍物位置
OBSTACLES:
- POSITIONS: [[0.05, 0.05], [0.05, 0.05], [0.05, 0.05]]  # 三个远离中心的障碍物位置
  SIZES: [[0.002, 0.002]]  # 障碍物尺寸（像素）

# 目标位置 - 定义任务目标
GOAL: [[1.0, 0.0, 1.2]]  # 木板举升目标位置

# 环境边界 - 定义工作空间的边界
BOUNDARIES:
  X_MIN: 0.0
  X_MAX: 2.0
  Y_MIN: -1.0
  Y_MAX: 1.0
  Z_MIN: 0.0
  Z_MAX: 2.0

# 任务参数
TASK_PARAMS:
  BOARD_SIZE: [1.0, 0.4, 0.03]  # 木板尺寸
  TABLE_SIZE: [0.4, 1.5, 0.05]  # 桌面尺寸
  MIN_BALANCE: 0.8  # 最小平衡阈值
  COLLABORATION_DISTANCE: 0.6  # 协作距离
