pkl_data_base: ../diffusion_copolicy/diffusion_policy/env/demo
map_config: rnd_obstacle_v2
run_name: diffusion-training
npz_data_base: datasets
keyboard_actions: False
## Data filtering options
skip_frames: False
skip_start_idx: 0
skip_freq: 3
remove_stopped_motion: False
remove_len_of_n: 5
low_pass_filter: False # Applies to actions only