defaults:
  - _self_
  - task: collaborative_lifting_lowdim

name: train_flow_matching_collaborative_lifting
_target_: flow_policy.workspace.train_flow_matching_transformer_lowdim_workspace.TrainFlowMatchingTransformerLowdimWorkspace

obs_dim: ${task.obs_dim}
human_act_as_cond: False
action_dim: ${task.action_dim}
task_name: ${task.name}
exp_name: "collaborative_lifting"

# 动作维度分解
robot_action_dim: 4    # 机械臂动作维度
human_action_dim: 6    # 人类动作维度
# 总动作维度 = robot_action_dim + human_action_dim = 4 + 6 = 10

horizon: 8
n_obs_steps: 2
n_action_steps: 6
n_latency_steps: 0
keypoint_visible_rate: 1.0
obs_as_cond: True
pred_action_steps_only: False

policy:
  _target_: flow_policy.policy.flow_matching_transformer_lowdim_policy.FlowMatchingTransformerLowdimPolicy

  model:
    _target_: flow_policy.model.diffusion.flow_matching_transformer.FlowMatchingTransformer
    input_dim: 10
    output_dim: 10
    horizon: ${horizon}
    n_obs_steps: ${n_obs_steps}
    cond_dim: 23

    n_layer: 6
    n_head: 4
    n_emb: 128
    p_drop_emb: 0.1
    p_drop_attn: 0.2

    causal_attn: True
    time_as_cond: True
    obs_as_cond: ${obs_as_cond}
    human_act_as_cond: ${human_act_as_cond}
    n_cond_layers: 0
  
  horizon: ${horizon}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  n_action_steps: ${n_action_steps}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 30
  obs_as_cond: ${obs_as_cond}
  human_act_as_cond: ${human_act_as_cond}
  pred_action_steps_only: ${pred_action_steps_only}
  
  # 动作维度配置
  robot_action_dim: ${robot_action_dim}
  human_action_dim: ${human_action_dim}

# task配置由collaborative_lifting_lowdim.yaml继承，无需重复定义
# task:
#   _target_: flow_policy.task.table_lowdim_task.TableLowdimTask
#   dataset: ${task.dataset}
#   env_runner: ${task.env_runner}

dataloader:
  batch_size: 32
  num_workers: 1
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 32
  num_workers: 1
  shuffle: False
  pin_memory: True
  persistent_workers: False

training:
  device: "cuda"
  log: true
  n_epochs: 500
  lr: 2e-4
  weight_decay: 1.0e-4
  betas: [0.9, 0.999]
  sample_every: 5
  checkpoint_every: 10
  eval_every: 10  # 改为10，与checkpoint_every相同
  log_every: 50
  num_warmup_steps: 1000
  scheduler_type: "cosine"
  seed: 42

logging:
  project: "flow_matching_collaborative_lifting"
  tags: ["flow_matching", "collaborative_lifting", "no_human_cond"]
  notes: "Flow Matching Transformer for collaborative lifting task using collaborative_lifting_sac_350.zarr data (23D obs, 10D action: 4D robot + 6D human)"

checkpoint:
  topk:
    monitor_key: val_loss
    mode: min
    k: 3
    format_str: 'epoch={epoch:04d}-val_loss={val_loss:.6f}.ckpt'
  save_last_ckpt: true
